name: rtcloud
channels:
  - defaults
  - conda-forge
  - brainiak
dependencies:
  - numpy
  - scipy
  - pydicom
  - toml
  - ipython
  - jupyter
  - pytest
  - flake8
  - mypy
  - pip
  - tornado
  - websocket-client
  - bcrypt
  - requests
  - openssl
  - nibabel
  - wsaccel
  - scikit-learn
  - nilearn
  - brainiak
  - dcm2niix
  - nodejs
  - pip:
    - watchdog
    - inotify
