# Config file for rtSynth_rt project
# we have a seperate file for each subject and 
# for 8 recognition runs on day1; 

# for 2 x 2 recognition run on day2 ; 
# for 1 feedback session on day2 ; 

# for 2 x 2 recognition run on day3 ; 
# for 1 feedback session on day3 ; 

# for 2 x 2 recognition run on day4 ; 
# for 1 feedback session on day4 ; 

# for 8 recognition run on day5 ; 

# subject Yuexuan Li,

title = 'rtSynth_rt'

session=3 # which session is this? which day is this on? could be 1 2 3 4 5 
subjectDay = 3 #this is for the naming of web/conf/{subjactName}_day{subjectDay}_run{runNum}.toml
runNum = [1] #[1,2,3,4,5,6,7,8] # This is the list of unique run, e.g. when the recognition1 is repeated twice, this can be 1 and 2
scanNum = [1] #[1,2,3,4,5,6,7,8] # This is a list of scan(or runs that might be repetitive)


subjectName = "sub001" # subject folder name in the rtSynth_rt/subjects folder
LASTNAME="rtSynth_sub001"
subjectIDforxnat="rtSynth_sub001_ses3" #PATIENTID has to be unique for each subject


realtimeFolder_subjectName="rtSynth_sub001"
preDay_YYYYMMDD="20210122" # can be "0" if there is no previous day for this session
YYYYMMDD="20210210" #note that 20210114 is for simulation should actually be "20210122"
num_total_TRs=174 # number of total TRs in feedback session

TrialNumber= 12 # feedback trial number for a feedback run.


plotTitle = 'Realtime Plot'
plotXLabel = 'Sample #'
plotYLabel = 'Value'
plotXRangeLow = 0
plotXRangeHigh = 176
plotYRangeLow = 0
plotYRangeHigh = 20
plotAutoRangeX = false
plotAutoRangeY = true
# dicomNamePattern = "001_{SCAN:06d}_{TR:06d}.dcm"
minExpectedDicomSize=300000

