# Config file for rtSynth_rt project
# we have a seperate file for each subject and 
# for 8 recognition runs on day1; 

# for 2 x 2 recognition run on day2 ; 
# for 1 feedback session on day2 ; 

# for 2 x 2 recognition run on day3 ; 
# for 1 feedback session on day3 ; 

# for 2 x 2 recognition run on day4 ; 
# for 1 feedback session on day4 ; 

# for 8 recognition run on day5 ; 


# subject Sheri Choi,
# Date of birth: 11/24/1990
# Height: 5 feet 3 inch
# Weight: 125
# Sex: female


title = 'rtSynth_rt'

session=6 # which session is this? which day is this on? could be 1 2 3 4 5 
subjectDay = 6 #this is for the naming of web/conf/{subjactName}_day{subjectDay}_run{runNum}.toml
subjectIDforxnat="rtSynth_sub002_ses6" # PATIENTID has to be unique for each subject
preDay_YYYYMMDD="20210518" # can be "0" if there is no previous day for this session
YYYYMMDD="20210520"

subjectName = "sub002" # subject folder name in the rtSynth_rt/subjects folder
LASTNAME="rtSynth_sub002"
realtimeFolder_subjectName="rtSynth_sub002"

studyDescription="rtSynth_rt"

num_total_TRs=174 # number of total TRs in feedback session # 12*14+6=174
TrialNumber= 12 # feedback trial number for a feedback run.

runNum = [1] #[1,2,3,4,5,6,7,8] # This is the list of unique run, e.g. when the recognition1 is repeated twice, this can be 1 and 2
scanNum = [1] #[1,2,3,4,5,6,7,8] # This is a list of scan(or runs that might be repetitive)

plotTitle = 'Realtime Plot'
plotXLabel = 'Sample #'
plotYLabel = 'B prob'
plotXRangeLow = 0
plotXRangeHigh = 176
plotYRangeLow = 0
plotYRangeHigh = 20
plotAutoRangeX = false
plotAutoRangeY = true
# dicomNamePattern = "001_{SCAN:06d}_{TR:06d}.dcm"
minExpectedDicomSize=300000

